# config.yml

app:
  name: "WebSearchAPI"
  host: "0.0.0.0"
  port: 8000
  reload: true

rate_limit:
  limit: "100/second"

log:
  level: "INFO"

proxy:
  authKey: F6F7FD85
  password: 5086B9755012
  proxyAddr: tun-lreqvr.qg.net:19104
  username : 15971019490

tianyan:
  base_url: "https://www.tianyancha.com/nsearch"
  use_proxy: true
  retry_times: 3
  delay: 2  # 请求间隔时间(秒)
