# config.yml

app:
  name: "WebSearchAPI"
  host: "0.0.0.0"
  port: 8000
  reload: true

rate_limit:
  limit: "100/second"

log:
  level: "INFO"

proxy:
  username: 18925155363
  password: 4EGPkKtQ

tianyan:
  base_url: "https://www.tianyancha.com/nsearch"
  use_proxy: true
  retry_times: 3
  delay: 2  # 请求间隔时间(秒)